### ISSUE TITLE
Non-allDay events set with allDay == 1

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/calendar-aggregator#10]
On rogue, when looking at events, they're all being returned with allDay set as True, so no times are being displayed:
[https://rogue.bloomington.in.gov/drupal/calendar](url)

**Comment by inghamn** [comment]
I think this is a bug in the old version of PHP that is on Rogue.  I'm updating Rogue to the same version of PHP that's on Tarantula.

**Comment by inghamn** [comment]
Fixed in 951d194bac1ad5ff9aba8857dc5e8e901975ce39
